### ISSUE TITLE
NameError: name 'data_test' is not defined

### ISSUE THREAD

**Issue by Y-Helios** [javirandor/wdr#1]
Hello! I just read your paper and tried to run the code, but I have met some problems. When I run the code, the compiler told me that **'data_test' is not defined** and when I look through the code, I found it's true. The error is in the **Computing Logits Difference** part, the last two cells, I wonder where to define this variable. I would appreciate it if you can reply me.Thanks a lot.

**Comment by Y-Helios** [comment]
Oh  I think I've solved this problem, it seems like you put the last two cells backwards.

**Comment by ArJone-cyh** [comment]
> 哦，我想我已经解决了这个问题，你好像把最后两个单元格放反了。
Hello, I think I've also encountered this problem. Can you elaborate on how you resolved it

**Comment by Y-Helios** [comment]
> > 哦，我想我已经解决了这个问题，你好像把最后两个单元格放反了。
> > Hello, I think I've also encountered this problem. Can you elaborate on how you resolved it

Just exchange the two cells.
